[package]
name = "proph_transformers"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
proph = { path = "../proph" }
proph_derive = { path = "../proph_derive" }
rscam = "0.5.5"
serde = { version = "1.0", features = ["derive"] }
turbojpeg = {version = "0.5", features = ["image"]}
zune-jpeg = "0.3.17"