[package]
name = "cytos_transformers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.25.1"
cytos = { path = "../cytos" }
cytos_derive = { path = "../cytos_derive" }
rscam = "0.5.5"
serde = { version = "1.0", features = ["derive"] }
rustface = "0.1.7"
reqwest = { version = "0.12.9", features = ["blocking","json"] }