[package]
name = "cytos_web"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
cytos = { path = "../cytos" }
serde_json = "1.0"
clap = "4.4.6"
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
scopeguard = "*"
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
